# Generated by Django 6.0.1 on 2026-01-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacienteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dolor', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_reservas', to='pacienteApp.paciente')),
            ],
        ),
    ]
